### GET /
GET http://localhost:5000

### POST Register a user /auth/register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

### POST Login a user /auth/login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}